### ISSUE TITLE
RK4 seems broken

### ISSUE THREAD

**Issue by mseri** [owlbarn/owl_ode#5]
We need to double check, but I am getting inconsistent results (while the other methods seem to consistently agree)

**Comment by ryanrhymes** [comment]
can we add a test suite similar to owl so others can recreate the issue?

**Comment by mseri** [comment]
It's on the pipeline. I am still trying to figure out the best way of testing this. Maybe by taking a set of known ode+solutions and checking that the error is somewhat O(h^(method-order)).

**Comment by ryanrhymes** [comment]
Agree, we can use matlab (or other tools) to generate a set of solutions beforehand, then use owl-ode to check against it.

**Comment by mseri** [comment]
We could even pick some equations with closed form solutions if we want to be more reliable, at that point is really about comparing numerical and analytical solutions.

**Comment by tbrk** [comment]
One example that we often use in Zélus is:

```
let f t y yd =
  yd.{0} <- (-. y.{1}); (* cosine *)
  yd.{1} <- y.{0} (* sine *)

let y_init = [| 1.0; 0.0 |]
```

**Comment by mseri** [comment]
Indeed, that's a quite good example.

PS. [Zélus](http://zelus.di.ens.fr/) seems awesome, I did not know about it, thanks for mentioning it!

**Comment by tachukao** [comment]
@mseri I just found the bug in the RK4 stepper function, should have been more careful when I wrote the function :facepalm:. 
I also noticed something weird with RK4 a while back, but I never looked into it.
Basically, the problem was with the update:
```let dy = M.((k1 + k2 + k3 + k4) /$ 6.) ```
It should be
```let dy = M.((k1 + (2. $* k2) + (2. $* k3) + k4) /$ 6.)```
I've made the necessary changes and pushed. But yea I agree, we should add a  test suite to test all these stepper functions 👍

**Comment by mseri** [comment]
Thanks! I’ll try to prepare some tests following tbrk suggestion soon

**Comment by mseri** [comment]
I have a proposal for testing: https://github.com/owlbarn/owl_ode/pull/6
If you agree with the approach, I am going to merge and release a new version (including also @tachukao fixes)
